### ISSUE TITLE
peer1.conf not created

### ISSUE THREAD

**Issue by danielslyman** [DigitallyRefined/docker-wireguard-tunnel#24]
Hey, 

I love the concept of this but for some reason the server is not creating peer1.conf but only wg0.conf. Any ideas how to resolve this?

Best,
Daniel

**Comment by DigitallyRefined** [comment]
If you create a new folder with a `docker-compose.yml` file in it:

```yml
services:
  wireguard-tunnel-server:
    image: ghcr.io/digitallyrefined/docker-wireguard-tunnel:v3
    container_name: wireguard-tunnel-server
    environment:
      # Update to your domain
      - DOMAIN=wireguard-tunnel.example.com
      # Number of peers to auto generate config for
      - PEERS=1
      # Services to expose format (comma-separated)
      # SERVICES=peer-id:peer-container-name:peer-container-port:expose-port-as
      - SERVICES=peer1:nginx:80:8080,peer1:nginx-demo:80:8081
    cap_add:
      - NET_ADMIN
    volumes:
      - ./config:/etc/wireguard
    restart: unless-stopped
    ports:
      - '51820:51820/udp'
      - 8080:8080
      - 8081:8081
```

Then run `docker compose up -d` this should create a new `config` folder with a newly generated `peer1.conf` file in it.

If not, please post any error messages from either the `docker compose up -d` or `docker compose logs -f` commands.
