### ISSUE TITLE
Error: Unknown device type.

### ISSUE THREAD

**Issue by ElPenguin** [DigitallyRefined/docker-wireguard-tunnel#6]
Hi ! I have an issue with my client...

Here my config : 

docker-compose.yml
```yaml
---
version: "2.1"
services:
  wireguard-tunnel-peer:
    image: ghcr.io/digitallyrefined/docker-wireguard-tunnel:v3
    container_name: wireguard-tunnel-peer
    environment:
      # Note that DOMAIN & PEERS are not required for the peer
      # Services to expose format (comma-separated)
      # SERVICES=peer-id:peer-container-name:peer-container-port:expose-port-as
      - SERVICES=peer1:nginx:80:8080,peer1:nginx-demo:80:8081
    cap_add:
      - NET_ADMIN
    volumes:
      - /home/tom/wireguard:/etc/wireguard
    restart: unless-stopped
    links:
      - nginx:nginx
      - nginx-demo:nginx-demo

  nginx:
    image: nginx
    restart: unless-stopped

  nginx-demo:
    image: nginxdemos/hello
    restart: unless-stopped
```

wg0.conf

```
[Interface]
PrivateKey = [KEYYYYYY]
Address = 10.0.0.1/32
MTU = 1280
SaveConfig = false

[Peer]
PublicKey = [KEYYYYYY]
Endpoint = wireguard.DOMAIN.com:51820
AllowedIPs = 10.0.0.254/32
PersistentKeepalive = 25
```

and my logs :

```
Starting Internet redirection server
Starting Wireguard
Warning: `/etc/wireguard/wg0.conf' is world accessible
[#] ip link add wg0 type wireguard
Error: Unknown device type.
Unable to access interface: Protocol not supported
[#] ip link delete dev wg0
Cannot find device "wg0"
```

Can you help me please :3
